baseURL = "https://maznanfb.com/"
languageCode = "en-us"
title = "maznanfb"
theme = "simpleblog"
disqusShortname = "maznanfb" # delete this to disable disqus comments
googleAnalytics = "UA-74408604-4"
staticDir = ["static"]
enableEmoji = true

[params]
    author = "Aznan Firmansyah"
    description = "Aznan Firmanyah's Personal Blog"
    githubUsername = "maznanfb"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Niramit" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "monokai"
    highlightLanguages = ["go", "python", "cpp", "scala", "swift"]
    profilePic = "logo.jpg"
    favicon = "icon.png"


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:muh.aznan@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/maznanfb/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/maznanfb/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/maznanfb/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.facebook.com/profile.php?id=1625386996"
    name = "facebook"
    weight = 5
[[menu.icon]]
    url = "https://www.instagram.com/maznanfb/"
    name = "instagram"
    weight = 6
